apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deployment
    labels:
        app: app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app
    template:
        metadata:
            labels:
                app: app
        spec:
            containers:
                - name: app
                  image: wil42/playground:v2
                  ports:
                      - containerPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: app-ingress
spec:
    rules:
        - http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: app-service
                            port:
                                number: 80
---
apiVersion: v1
kind: Service
metadata:
    name: app-service
spec:
    selector:
        app: app
    ports:
        - name: app-port
          protocol: TCP
          port: 80
          targetPort: 8888
    type: ClusterIP
